version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 180
      runas: root
